config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do
    resource :profile
  end


  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name,  presence: true
  # , length: { maximum: 50 }
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true
  #, length: { maximum: 255 },
  # format: { with: VALID_EMAIL_REGEX },
  #          uniqueness: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates :first_name, :last_name, presence: true, length: { maximum: 50 }
  has_attached_file :avatar, :styles => {:medium => "300x300>", :thumb => "100x100>"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token

  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]

      ContactMailer.contact_email(name, email, body).deliver
      
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      flash[:danger] = "Error occured, message has not been sent."
      redirect_to new_contact_path
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :comments)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user

  def new
    # form where a user can fill out their own profile.
    @user = User.find(params[:user_id])
    @profile = Profile.new
    # @profile = @user.build_profile
  end

  def create
    @user = User.find(params[:user_id])
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile Created!"
      redirect_to user_path(params[:user_id])
    else
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile
  end

  def update
    @user = User.find(params[:user_id])
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile Updated!"
      redirect_to user_path(params[:user_id])
    else
      render action :edit
    end

  end


  private
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
  end

  def only_current_user
    @user = User.find( params[:user_id] )
    redirect_to(root_url) unless @user == current_user
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_plan, only: :new

  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end


  private
  def select_plan
    unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find ( params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # def instrument_icon
  #   if @user.profile.i == "Developer"
  #     "<i class='fa fa-code'></i>".html_safe
  #   elsif @user.profile.job_title == "Entrepreneur"
  #     "<i class='fa fa-lightbulb-o'></i>".html_safe
  #   elsif @user.profile.job_title == "Investor"
  #     "<i class='fa fa-dollar'></i>".html_safe
  #   end
  # end
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1 class="text-center about">Contact Us</h1>
    <h4 class="text-center about">Reach out if you have any questions, comments or suggestions.</h4>
    <div class="well">
      <%= form_for @contact do |f| %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
          <%= f.submit 'Submit', class: 'btn btn-primary btn-lg page-scroll' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicianLink.io</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag href='../assets/css/bootstrap.css', type='text/css' %>
  <%= stylesheet_link_tag href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic', rel='stylesheet', type='text/css', media: 'all' %>
  <%= stylesheet_link_tag href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800', rel='stylesheet', type='text/css', media: 'all' %>
  <%= stylesheet_link_tag href='../assets/css/creative.css', type='text/css' %>
  <%= stylesheet_link_tag href='../assets/css/animate.min.css', type='text/css' %>
  <%= stylesheet_link_tag href='../assets/css/animate.min.css', type='text/css' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag src="../javascripts/jquery.js", type="text/javascript" %>
  <%= javascript_include_tag src="../javascripts/classie.js", type="text/javascript" %>
  <%= javascript_include_tag src="../javascripts/creative.js", type="text/javascript" %>
  <%= javascript_include_tag src="../javascripts/bootstrap.js", type="text/javascript" %>
  <%= javascript_include_tag src="../javascripts/wow.min.js", type="text/javascript" %>
  <%= javascript_include_tag src="../javascripts/application.js", type="text/javascript" %>

  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-music"> </i>
        MusicianLink.io
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm navbar-btn' %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary btn-sm navbar-btn', method: :get %>

        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Community", users_path %></li>
          <li><%= link_to "My Account", edit_user_registration_path %></li>
        <% end %>
        <!--<li><%= link_to "About", about_path %></li>-->
        <li><%= link_to "Contact Us", new_contact_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1 class="about text-center">About Us</h1>
<h4 class="about text-center">Welcome to MusicLink! We are a community of musicians, songwriters, and producers who are interested in meeting one another and making good music.</h4>
<section id="portfolio" class="no-padding">
  <div class="container-fluid">
    <div class="row no-gutter">
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img
      src="../images/portfolio/guitarists.jpg" alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with guitarists</div>
            <div class="project-name">Guitar</div>
          </div>
        </div>
      </a></div>
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img
      src="../images/portfolio/vocalists.jpg" alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with singers</div>
            <div class="project-name">Vocals</div>
          </div>
        </div>
      </a></div>
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img
      src="../images/portfolio/drummers.jpg" alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with drummers</div>
            <div class="project-name">Drums</div>
          </div>
        </div>
      </a></div>
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img
      src="../images/portfolio/bassists.jpg" alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with bassists</div>
            <div class="project-name">Bass</div>
          </div>
        </div>
      </a></div>
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img
      src="../images/portfolio/keyboards.jpg" alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with keyboardists</div>
            <div class="project-name">Keys</div>
          </div>
        </div>
      </a></div>
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img src="../images/portfolio/horns.jpg"
                                                                            alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with horn players</div>
            <div class="project-name">Horns</div>
          </div>
        </div>
      </a></div>
    </div>
  </div>
</section>

app/views/pages/home.html.erb
<div class="jumbotron text-center wow bounceIn">
  <h1>Welcome to MusicianLink</h1>

  <h3>Where musicians connect.</h3>
</div>
<div class="row">
  <% if user_signed_in? %>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Your Profile</h2>
          <div><p> </p></div>
          <% if current_user.profile %>
              <%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-primary btn-lg btn-block' %>
            <p> </p>
              <%= link_to "View your profile", user_path(current_user), class: 'btn btn-info btn-lg btn-block btn-view' %>
          <% else %>
              <p class="text-center">Create your profile so that you can share your information with the community.</p>
              <%= link_to "Create your profile", new_user_profile_path(current_user), class: 'btn btn-primary btn-lg btn-block' %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">The Community</h2>

          <p class="text-center">Visit the community to easily connect with professional musicians in your area.</p>
          <%= link_to "Visit the community", users_path, class: 'btn btn-success btn-lg btn-block' %>
        </div>
      </div>
  <% else %>

      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Basic Membership</h2>
          <h4 class="text-center">Sign up for free and get basic access to the community.</h4>
          <br/>
          <%= link_to "Sign up Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block wow bounceIn' %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Pro Membership</h2>
          <h4 class="text-center">Sign up for the pro account for $5/month and get access to the community and contact
            information!</h4>
          <%= link_to "Sign up Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
        </div>
      </div>
  <% end %>
</div>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head><title>MusicianLink</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag href='/static/css/bootstrap.css', type='text/css' %>

  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top">
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid"><!-- Brand and toggle get grouped for better mobile display-->
    <div class="navbar-header">
      <button type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
              class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span><span
      class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
      <a href="/" class="navbar-brand page-scroll">MusicianLink.io</a></div>
    <!-- Collect the nav links, forms, and other content for toggling-->
    <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/blog">Blog</a></li>
      </ul>
    </div>
  </div>
</nav>
<header>
  <div class="header-content">
    <div class="header-content-inner"><h1>Where musicians connect.</h1>
      <hr>
      <p>MusicianLink allows you to easily connect with professional musicians in your area.</p>                <a
    href="/users/new" class="btn btn-primary btn-xl page-scroll">Sign up now!</a></div>
  </div>
</header>
<section id="about" class="bg-primary">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center"><h2 class="section-heading">Get your groove on.</h2>
        <hr class="light">
        <p class="text-faded">Join today and get connected with professional musicians.</p>
        <a href="/users/new" class="btn btn-default btn-xl">Get Started!</a></div>
    </div>
  </div>
</section>
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center"><h2 class="section-heading">Networking, at your finger tips.</h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6 text-center">
        <div class="service-box"><i class="fa fa-4x fa-globe wow bounceIn text-primary"></i>

          <h3>Easy Connections</h3>

          <p class="text-muted">Join the thousands of seeking musicians and bands.</p></div>
      </div>
      <div class="col-lg-4 col-md-6 text-center">
        <div class="service-box"><i data-wow-delay=".2s"
                                    class="fa fa-4x fa-newspaper-o wow bounceIn text-primary"></i>

          <h3>Access Anywhere</h3>

          <p class="text-muted">Your next gig is waiting.</p></div>
      </div>
      <div class="col-lg-4 col-md-6 text-center">
        <div class="service-box"><i data-wow-delay=".3s"
                                    class="fa fa-4x fa-heart wow bounceIn text-primary"></i>

          <h3>Safe and Secure</h3>

          <p class="text-muted">We protect your data with the utmost integrity. Your privacy is our
            priority.</p></div>
      </div>
    </div>
  </div>
</section>
<aside class="bg-dark">
  <div class="container text-center">
    <div class="call-to-action"><h2>Meet musicians like you!</h2>                <a href="/users/new"
                                                                                    class="btn btn-default btn-xl wow tada">Join
      now for free!</a></div>
  </div>
</aside>
<section id="portfolio" class="no-padding">
  <div class="container-fluid">
    <div class="row no-gutter">
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img
      src="../images/portfolio/guitarists.jpg" alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with guitarists</div>
            <div class="project-name">Guitar</div>
          </div>
        </div>
      </a></div>
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img
      src="../images/portfolio/vocalists.jpg" alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with singers</div>
            <div class="project-name">Vocals</div>
          </div>
        </div>
      </a></div>
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img
      src="../images/portfolio/drummers.jpg" alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with drummers</div>
            <div class="project-name">Drums</div>
          </div>
        </div>
      </a></div>
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img
      src="../images/portfolio/bassists.jpg" alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with bassists</div>
            <div class="project-name">Bass</div>
          </div>
        </div>
      </a></div>
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img
      src="../images/portfolio/keyboards.jpg" alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with keyboardists</div>
            <div class="project-name">Keys</div>
          </div>
        </div>
      </a></div>
      <div class="col-lg-4 col-sm-6"><a href="#" class="portfolio-box"><img src="../images/portfolio/horns.jpg"
                                                                            alt="" class="img-responsive">

        <div class="portfolio-box-caption">
          <div class="portfolio-box-caption-content">
            <div class="project-category text-faded">Connect with horn players</div>
            <div class="project-name">Horns</div>
          </div>
        </div>
      </a></div>
    </div>
  </div>
</section>
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center"><h2 class="section-heading">Who we are</h2>
        <hr class="primary">
        <p>At MusicianLink.io, we love to connect like musicians together for the benefit of all.</p></div>
      <div class="col-lg-4 col-lg-offset-2 text-center"><i class="fa fa-phone fa-3x wow bounceIn"></i>

        <p>800-4Pro-Jam</p></div>
      <div class="col-lg-4 text-center"><i data-wow-delay=".1s" class="fa fa-envelope-o fa-3x wow bounceIn"></i>

        <p><a href="mailto: info@musicianlink.io">Email us!</a></p></div>
    </div>
  </div>
</section>
<%= javascript_include_tag src="/static/js/jquery.js", type: 'text/javascript' %>
<%= javascript_include_tag src="/static/js/bootstrap.min.js", type: 'text/javascript' %>
<%= javascript_include_tag src="/static/js/jquery.easing.min.js", type: 'text/javascript' %>
<%= javascript_include_tag src="/static/js/jquery.fittext.js", type: 'text/javascript' %>
<%= javascript_include_tag src="/static/js/wow.min.js", type: 'text/javascript' %>
<%= javascript_include_tag src="/static/js/creative.js", type: 'text/javascript' %>
</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :avatar %>
      <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :job_title %>
      <%= f.select :job_title, ['Guitar Player', 'Bass Player', 'Drummer', 'Vocalist', 'Keyboard Player', 'Horn Player', 'Producer', 'Songwriter', 'Rapper'], {}, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :contact_email %>
      <%= f.text_field :contact_email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit "Update Profile", class: 'btn btn-primary btn-lg page-scroll' %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center about">Edit Your Profile</h1>

    <h3 class="text-center about">Be a part of the MusicianLink community and fill out your profile!</h3>

    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center about">Create Your Profile</h1>

    <h3 class="text-center about">Be a part of the MusicianLink community and fill out your profile!</h3>

    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1 class="about text-center">MusicianLink Community</h1>
    <h4 class="about text-center">Welcome to the MusicianLink community. Users must fill out a profile in order to be visible in the community.</h4>
    <ul class="list-unstyled">
      <% @users.each do |user| %>
          <% if user.profile %>
              <li>
                <div class="well well-sm row <%= cycle('white-bg', '') %>">
                  <div class="col-sm-4 text-center">
                    <% if user.profile.avatar %>
                        <%= link_to user do %>
                            <%= image_tag user.profile.avatar.url(:thumb), class: 'user-index-avatar' %>
                        <% end %>
                    <% end %>
                  </div>

                  <div>
                    <%= link_to user do %>
                        <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                    <% end %>
                    <p>
                      <%= user.profile.job_title %>
                      <% if user.plan_id == 2 %>
                          <span class="label label-danger">PRO</span>
                      <% end %>
                    </p>
                  </div>
                </div>
              </li>
          <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3 text-center">
    <%= image_tag @user.profile.avatar.url(:medium), class: "user-show-avatar" %>
  </div>
  <div class="col-md-6">
    <h1 class="about"><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>

    <h3 class="about text-center"><span class="job-title-icon"><%= %></span> <%= @user.profile.job_title %></h3>

    <div class="well profile-block profile-description text-center">
      <!--<h4 class="about text-center">Info / Bio</h4>-->
      <%= @user.profile.description %>
    </div>

    <% if current_user.plan_id == 2  %>
        <div class="well profile-block contact-info">
          <h3>Contact Info</h3>
          <%= @user.profile.phone_number %><br/>
          <%= @user.profile.contact_email %><br/>
        </div>
    <% end %>

  </div>
</div>